package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/** Neutral cinema surfaces keep artwork prominent; red is reserved for emphasis. */
internal object NyanimeColorScheme : BaseColorScheme() {
    override val darkScheme = darkColorScheme(
        primary = Color(0xFFFF3344),
        onPrimary = Color(0xFF230002),
        primaryContainer = Color(0xFFB20710),
        onPrimaryContainer = Color.White,
        inversePrimary = Color(0xFFB90D2C),
        secondary = Color(0xFFF5F5F5),
        onSecondary = Color(0xFF141414),
        secondaryContainer = Color(0xFF282828),
        onSecondaryContainer = Color(0xFFF5F5F5),
        tertiary = Color(0xFFFFC878),
        onTertiary = Color(0xFF302000),
        tertiaryContainer = Color(0xFF44351F),
        onTertiaryContainer = Color(0xFFFFDFAB),
        background = Color(0xFF080808),
        onBackground = Color(0xFFF5F5F5),
        surface = Color(0xFF080808),
        onSurface = Color(0xFFF5F5F5),
        surfaceVariant = Color(0xFF252525),
        onSurfaceVariant = Color(0xFFB9B9B9),
        surfaceTint = Color.Transparent,
        inverseSurface = Color(0xFFE6E6EB),
        inverseOnSurface = Color(0xFF19191D),
        outline = Color(0xFF858585),
        outlineVariant = Color(0xFF343434),
        surfaceContainerLowest = Color(0xFF050505),
        surfaceContainerLow = Color(0xFF121212),
        surfaceContainer = Color(0xFF191919),
        surfaceContainerHigh = Color(0xFF232323),
        surfaceContainerHighest = Color(0xFF303030),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFFC45110),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFE4CF),
        onPrimaryContainer = Color(0xFF3A1900),
        inversePrimary = Color(0xFFFFAD70),
        secondary = Color(0xFF393632),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFECE9E4),
        onSecondaryContainer = Color(0xFF20201F),
        tertiary = Color(0xFF875500),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDFAD),
        onTertiaryContainer = Color(0xFF2C1C00),
        background = Color(0xFFFFFFFF),
        onBackground = Color(0xFF20201F),
        surface = Color(0xFFFFFFFF),
        onSurface = Color(0xFF20201F),
        surfaceVariant = Color(0xFFF1ECE6),
        onSurfaceVariant = Color(0xFF625B55),
        surfaceTint = Color(0x00000000),
        inverseSurface = Color(0xFF2F2D2A),
        inverseOnSurface = Color(0xFFFAF8F5),
        outline = Color(0xFF81756C),
        outlineVariant = Color(0xFFDED7CE),
        surfaceDim = Color(0xFFE9E4DF),
        surfaceBright = Color(0xFFFFFFFF),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFAF8F5),
        surfaceContainer = Color(0xFFF4F0EA),
        surfaceContainerHigh = Color(0xFFEEE8E0),
        surfaceContainerHighest = Color(0xFFE6DED4),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        scrim = Color(0xFF000000),
    )
}
